import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'de' | 'fr' | 'pt' | 'it' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    nav_consultancy: 'Consultoría',
    nav_engineering: 'Ingeniería',
    nav_load_banks: 'Bancos de Carga',
    nav_ai: 'Datcer AI',
    nav_contact: 'Contacto',
    nav_quote: 'Cotizar',
    hero_badge: 'Sistemas Activos',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Ingeniería Pura.',
    hero_subtitle: 'Diseño de Data Centers de clase mundial. Infraestructura crítica pensada para el futuro.',
    hero_cta_primary: 'Explorar Soluciones',
    hero_cta_secondary: 'Ver Brochure',
    hero_cta_tertiary: 'Contactar Especialistas',
    about_badge: 'Excelencia',
    about_title: 'Infraestructura de Misión Crítica',
    about_text_1: 'En Datcer, transformamos la complejidad técnica en continuidad operativa.',
    about_text_2: 'Somos especialistas en el ciclo de vida completo de Data Centers, desde la concepción hasta la certificación.',
    services_title: 'Soluciones Integrales',
    engineering_title: 'Ingeniería de Detalle',
    load_banks_title: 'Bancos de Carga',
    certification_title: 'Certificaciones',
    ai_title: 'Datcer AI Assistant',
    ai_subtitle: 'Consultoría al instante.',
    ai_desc: 'Resuelve dudas sobre normativas, enfriamiento o solicita una cotización con nuestra IA entrenada.',
    ai_placeholder: 'Pregunta a Datcer...',
    ai_welcome: 'Hola, es un gusto saludarte. Soy el asistente de ingeniería de Datcer. ¿En qué puedo apoyarte hoy con tu proyecto de Data Center?',
    ai_writing: 'Escribiendo...',
    footer_desc: 'Expertos en la creación de ecosistemas de datos resilientes y eficientes. Transformamos la complejidad técnica en infraestructura confiable.',
    footer_services: 'Servicios',
    footer_contact: 'Contacto Directo',
    footer_ops: 'Operaciones Globales',
    footer_privacy: 'Política de Privacidad',
    footer_terms: 'Términos de Uso',
    footer_rights: 'Todos los derechos reservados.',
    about_who: 'Quiénes Somos',
    about_who_desc: 'Ingeniería de precisión para la economía digital.',
    about_what: 'Qué Hacemos',
    about_what_desc: 'Soluciones integrales de infraestructura crítica.',
    about_mission: 'Misión',
    about_mission_desc: 'Garantizar la continuidad operativa absoluta.',
    about_vision: 'Visión',
    about_vision_desc: 'Ser el referente en ingeniería de Data Centers.',
  },
  en: {
    nav_consultancy: 'Consultancy',
    nav_engineering: 'Engineering',
    nav_load_banks: 'Load Banks',
    nav_ai: 'Datcer AI',
    nav_contact: 'Contact',
    nav_quote: 'Quote',
    hero_badge: 'Active Systems',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Pure Engineering.',
    hero_subtitle: 'World-class Data Center design. Critical infrastructure designed for the future.',
    hero_cta_primary: 'Explore Solutions',
    hero_cta_secondary: 'View Brochure',
    hero_cta_tertiary: 'Contact Specialists',
    about_badge: 'Excellence',
    about_title: 'Mission Critical Infrastructure',
    about_text_1: 'At Datcer, we transform technical complexity into operational continuity.',
    about_text_2: 'We are specialists in the complete Data Center life cycle, from conception to certification.',
    services_title: 'Comprehensive Solutions',
    engineering_title: 'Detail Engineering',
    load_banks_title: 'Load Banks',
    certification_title: 'Certifications',
    ai_title: 'Datcer AI Assistant',
    ai_subtitle: 'Instant Consulting.',
    ai_desc: 'Solve doubts about regulations, cooling or request a quote with our trained AI.',
    ai_placeholder: 'Ask Datcer...',
    ai_welcome: 'Hello, it is a pleasure to greet you. I am the Datcer engineering assistant. How can I help you today with your Data Center project?',
    ai_writing: 'Writing...',
    footer_desc: 'Experts in creating resilient and efficient data ecosystems. We transform technical complexity into reliable infrastructure.',
    footer_services: 'Services',
    footer_contact: 'Direct Contact',
    footer_ops: 'Global Operations',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Use',
    footer_rights: 'All rights reserved.',
    about_who: 'Who We Are',
    about_who_desc: 'Precision engineering for the digital economy.',
    about_what: 'What We Do',
    about_what_desc: 'Comprehensive critical infrastructure solutions.',
    about_mission: 'Mission',
    about_mission_desc: 'Guarantee absolute operational continuity.',
    about_vision: 'Vision',
    about_vision_desc: 'To be the benchmark in Data Center engineering.',
  },
  de: {
    nav_consultancy: 'Beratung',
    nav_engineering: 'Engineering',
    nav_load_banks: 'Lastbanken',
    nav_ai: 'Datcer AI',
    nav_contact: 'Kontakt',
    nav_quote: 'Angebot',
    hero_badge: 'Aktive Systeme',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Reine Technik.',
    hero_subtitle: 'Weltklasse-Rechenzentrumsdesign. Kritische Infrastruktur für die Zukunft.',
    hero_cta_primary: 'Lösungen erkunden',
    hero_cta_secondary: 'Broschüre ansehen',
    hero_cta_tertiary: 'Spezialisten kontaktieren',
    about_badge: 'Exzellenz',
    about_title: 'Missionskritische Infrastruktur',
    about_text_1: 'Bei Datcer verwandeln wir technische Komplexität in operative Kontinuität.',
    about_text_2: 'Wir sind Spezialisten für den kompletten Lebenszyklus von Rechenzentren, von der Konzeption bis zur Zertifizierung.',
    services_title: 'Umfassende Lösungen',
    engineering_title: 'Detail-Engineering',
    load_banks_title: 'Lastbanken',
    certification_title: 'Zertifizierungen',
    ai_title: 'Datcer AI Assistent',
    ai_subtitle: 'Sofortige Beratung.',
    ai_desc: 'Lösen Sie Zweifel an Vorschriften, Kühlung oder fordern Sie ein Angebot mit unserer geschulten KI an.',
    ai_placeholder: 'Fragen Sie Datcer...',
    ai_welcome: 'Hallo, es ist mir ein Vergnügen, Sie zu begrüßen. Ich bin der Datcer Engineering-Assistent. Wie kann ich Ihnen heute bei Ihrem Rechenzentrumsprojekt helfen?',
    ai_writing: 'Schreibt...',
    footer_rights: 'Alle Rechte vorbehalten.',
  },
  fr: {
    nav_consultancy: 'Conseil',
    nav_engineering: 'Ingénierie',
    nav_load_banks: 'Bancs de Charge',
    nav_ai: 'Datcer AI',
    nav_contact: 'Contact',
    nav_quote: 'Devis',
    hero_badge: 'Systèmes Actifs',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Ingénierie Pure.',
    hero_subtitle: 'Conception de centres de données de classe mondiale. Infrastructure critique conçue pour l\'avenir.',
    hero_cta_primary: 'Explorer les Solutions',
    hero_cta_secondary: 'Voir la Brochure',
    hero_cta_tertiary: 'Contacter des Spécialistes',
    about_badge: 'Excellence',
    about_title: 'Infrastructure de Mission Critique',
    about_text_1: 'Chez Datcer, nous transformons la complexité technique en continuité opérationnelle.',
    about_text_2: 'Nous sommes spécialistes du cycle de vie complet des centres de données, de la conception à la certification.',
    services_title: 'Solutions Complètes',
    engineering_title: 'Ingénierie de Détail',
    load_banks_title: 'Bancs de Charge',
    certification_title: 'Certifications',
    ai_title: 'Assistant Datcer AI',
    ai_subtitle: 'Consultance instantanée.',
    ai_desc: 'Résolvez vos doutes sur les réglementations, le refroidissement ou demandez un devis avec notre IA entraînée.',
    ai_placeholder: 'Demandez à Datcer...',
    ai_welcome: 'Bonjour, c\'est un plaisir de vous saluer. Je suis l\'assistant ingénieur de Datcer. Comment puis-je vous aider aujourd\'hui avec votre projet de centre de données ?',
    ai_writing: 'Écrit...',
    footer_rights: 'Tous droits réservés.',
  },
  pt: {
    nav_consultancy: 'Consultoria',
    nav_engineering: 'Engenharia',
    nav_load_banks: 'Bancos de Carga',
    nav_ai: 'Datcer AI',
    nav_contact: 'Contato',
    nav_quote: 'Orçamento',
    hero_badge: 'Sistemas Ativos',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Engenharia Pura.',
    hero_subtitle: 'Design de Data Center de classe mundial. Infraestrutura crítica projetada para o futuro.',
    hero_cta_primary: 'Explorar Soluções',
    hero_cta_secondary: 'Ver Catálogo',
    hero_cta_tertiary: 'Contatar Especialistas',
    about_badge: 'Excelência',
    about_title: 'Infraestrutura de Missão Crítica',
    about_text_1: 'Na Datcer, transformamos a complexidade técnica em continuidade operacional.',
    about_text_2: 'Somos especialistas no ciclo de vida completo de Data Centers, da concepção à certificação.',
    services_title: 'Soluções Abrangentes',
    engineering_title: 'Engenharia de Detalhe',
    load_banks_title: 'Bancos de Carga',
    certification_title: 'Certificações',
    ai_title: 'Assistente Datcer AI',
    ai_subtitle: 'Consultoria Instantânea.',
    ai_desc: 'Resolva dúvidas sobre regulamentos, refrigeração ou solicite um orçamento com nossa IA treinada.',
    ai_placeholder: 'Pergunte à Datcer...',
    ai_welcome: 'Olá, é um prazer cumprimentá-lo. Sou o assistente de engenharia da Datcer. Como posso ajudá-lo hoje com seu projeto de Data Center?',
    ai_writing: 'Escrevendo...',
    footer_rights: 'Todos os derechos reservados.',
  },
  it: {
    nav_consultancy: 'Consulenza',
    nav_engineering: 'Ingegneria',
    nav_load_banks: 'Banchi di Carico',
    nav_ai: 'Datcer AI',
    nav_contact: 'Contatti',
    nav_quote: 'Preventivo',
    hero_badge: 'Sistemi Attivi',
    hero_title_1: 'Datcer.',
    hero_title_2: 'Ingegneria Pura.',
    hero_subtitle: 'Design di Data Center di classe mondiale. Infrastruttura critica progettata per il futuro.',
    hero_cta_primary: 'Esplora le Soluzioni',
    hero_cta_secondary: 'Vedi Brochure',
    hero_cta_tertiary: 'Contatta Specialisti',
    about_badge: 'Eccellenza',
    about_title: 'Infrastruttura Mission Critical',
    about_text_1: 'In Datcer, trasformiamo la complessità tecnica in continuità operativa.',
    about_text_2: 'Siamo specialisti nel ciclo di vida completo dei Data Center, dalla concezione alla certificazione.',
    services_title: 'Soluzioni Complete',
    engineering_title: 'Ingegneria di Dettaglio',
    load_banks_title: 'Banchi di Carico',
    certification_title: 'Certificazioni',
    ai_title: 'Assistente Datcer AI',
    ai_subtitle: 'Consulenza istantanea.',
    ai_desc: 'Risolvi dubbi su normative, raffreddamento o richiedi un preventivo con la nostra IA addestrata.',
    ai_placeholder: 'Chiedi a Datcer...',
    ai_welcome: 'Ciao, è un piacere salutarti. Sono l\'assistente di ingegneria di Datcer. Come posso aiutarti oggi con il tuo progetto di Data Center?',
    ai_writing: 'Scrivendo...',
    footer_rights: 'Tutti i diritti riservati.',
  },
  zh: {
    nav_consultancy: '咨询',
    nav_engineering: '工程',
    nav_load_banks: '负载银行',
    nav_ai: 'Datcer AI',
    nav_contact: '联系',
    nav_quote: '报价',
    hero_badge: '活动系统',
    hero_title_1: 'Datcer.',
    hero_title_2: '纯工程。',
    hero_subtitle: '世界一流的数据中心设计。为未来设计的关键基础设施。',
    hero_cta_primary: '探索解决方案',
    hero_cta_secondary: '查看手册',
    hero_cta_tertiary: '联系专家',
    about_badge: '卓越',
    about_title: '关键任务基础设施',
    about_text_1: '在 Datcer，我们将技术复杂性转化为运营连续性。',
    about_text_2: '我们是数据中心完整生命周期的专家，从构思到认证。',
    services_title: '综合解决方案',
    engineering_title: '详细工程',
    load_banks_title: '负载银行',
    certification_title: '认证',
    ai_title: 'Datcer AI 助手',
    ai_subtitle: '即时咨询。',
    ai_desc: '通过我们训练有素的 AI 解决有关法规、冷却的疑问或索取报价。',
    ai_placeholder: '询问 Datcer...',
    ai_welcome: '您好，很高兴见到您。我是 Datcer 工程助手。今天我能为您提供什么关于数据中心项目的帮助？',
    ai_writing: '正在输入...',
    footer_rights: '版权所有。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
